### ISSUE TITLE
CappasityConnectionTimeoutException in background

### ISSUE THREAD

**Issue by 4ybakut2004** [CappasityTech/CappasityAndroid#9]
Hi!

I got a `CappasityConnectionTimeoutException` via Firebase Crashlytics and can't reproduce it.

The stack trace doesn't point to any specific lines of my code.
The device data in the crash info shows that it was my device with the app installed, but I was not using it at the day of the crash. The crash happened several times, each time the device was in the background:

![exception](https://user-images.githubusercontent.com/4298764/126940882-74a5273d-0bed-4b5a-81a5-b7a48a8b66e3.png)

The `CappasityAndroid` library is used in my application only in a single place on a single screen, which can only be accessed by traveling through several screens. This screen has exception handling as described on your [wiki](https://github.com/CappasityTech/CappasityAndroid/wiki/Exception-handling), so I didn't expect unhandled exceptions to be thrown at all.

The application can accept Push notifications. The symptoms of a crash look like it happens during the initialization of the application while receiving push notifications. But, this is just a guess.

This crash affects crash free and I cannot release such code in production. Crash appeared in Firebase Crashlytics after I updated the library from some of the older versions to version 0.4.13.

Here is the stack trace:

```
Fatal Exception: com.cappasity.common.exception.CappasityConnectionTimeoutException: Network connection timeout
       at com.cappasity.common.exception.NetworkExceptionCreator$Companion.create(:21)
       at com.cappasity.obfuscated.g.i.invokeSuspend(:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

Please tell me how this crash could have happened while I was not using the application, and how can I handle it correctly?

**Comment by 4ybakut2004** [comment]
I was able to reproduce a similar crash - `CappasityNetworkConnectionException`. Occurs when you run the application with the Internet turned off.

I think this is inappropriate behavior for a library whose initialization is in the application class :thinking:

**Comment by cappasity** [comment]
Fixed. Please try "Release 0.4.14" 
Thank you.
